### ISSUE TITLE
Gather use cases for Map {toValue}

### ISSUE THREAD

**Issue by bmeck** [tc39/proposal-collection-normalization#1]
[see doc for examples](https://docs.google.com/document/d/1LuGv-rwr0UDfzJCF5qtTvFIvOpqqVqnCc3hFl-akpPo/edit?usp=sharing)

**Comment by benjamingr** [comment]
Hey, I'm also a bit confused about why we need this. I definitely need `toKey` and have needed it a ton of times. (From [5 years ago](https://esdiscuss.org/topic/maps-with-object-keys)).

**Comment by ljharb** [comment]
toValue would be needed, for example, if you wanted to normalize all values in a map - wrapping them all in a Proxy, ensuring they all had the same keys, etc. Basically, anything you’d overwrite the prototype methods for, you’d want a hook like this so Map.prototype.whatever.call couldn't bypass your subclass’s semantics.

**Comment by bmeck** [comment]
Added some to FAQ in fa700106482fd13941d0e1f8f6d045548c7e05a2

**Comment by benjamingr** [comment]
I still haven't seen a single concrete use case though :) Not saying toValue shouldn't happen just that I am still confused

**Comment by bmeck** [comment]
@benjamingr what do you mean concrete, the doc above shows examples
