### ISSUE TITLE
toValue for Map?

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-collection-normalization#4]
Is there a reason not to include `toValue` for Maps in this proposal?

**Comment by bmeck** [comment]
I can think of reasons to include it, but if this is just asking for reasons against it that might be a bit harder.

For example, automatically coercing/checking all values to ensure they become a unified type of value:

```mjs
const ppl = new Map([], {
  toValue: (_) => _ instanceof Person ? _ : Person.from(_)
});
// now, a successful .get() is always guaranteed to be a Person
// and have the proto methods of them
alwaysArrays.set('bob', {name: foo});
```

**Comment by ljharb** [comment]
I guess I'm more asking, can we include it :-)
