### ISSUE TITLE
Does toValue change what's stored in the Set?

### ISSUE THREAD

**Issue by ljharb** [tc39/proposal-collection-normalization#5]
Specifically:
```jsx
const s = new Set([1], { toValue: x => String(x) });
s.has(1); // true
s.has('1'); // true
[...s]; // ['1'] or [1]?
```

Could a clarifying example be added to show which one of these it is?

(related to #9)

**Comment by bmeck** [comment]
@ljharb all the entry list data records are updated accordingly, do we need to go over all permutations?

**Comment by ljharb** [comment]
Not all; but one each for Map and Set seems helpful ¯\\\_(ツ)_/¯
