### ISSUE TITLE
What happens when iterating over a rekeyed Map?

### ISSUE THREAD

**Issue by zenparsing** [tc39/proposal-collection-normalization#7]
If I call `Symbol.iterator` on a Map where rekey has been specified, what does the list contain?

```js
let userMap = new Map(undefined, {
  rekey({email}) {
    return email;
  }
});

userMap.set({ email: "x@y.z" }, 42);
userMap.has({ email: "x@y.z" }); // true, correct?

let users = [...userMap];
```

Am I correct in assuming that it would result in the following?

```js
[ ["x@y.z", 42] ];
```

If so, do we think that the following would be an issue?

```js
let user = { email: "x@y.z" };
userMap.has(user); // true
[...userMap.keys()].includes(user); // false
```

Thanks!

**Comment by bmeck** [comment]
Added a clarifying example in https://github.com/tc39/proposal-richer-keys/commit/610f5d01ebe1c7445959827c929a8d0fc5d7102e
